{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "database.fullname" . }}-pv
  labels:
    {{- include "database.labels" . | nindent 4 }}
    database-pv: {{ include "database.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end }}
