name: rabbitmq
image:
  repository: rabbitmq
  tag: 3.13-management
persistence:
  size: 8Gi
  storageClass: manual-sc
service:
  port: 5672
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
