apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-service.fullname" . }}
  labels:
    {{- include "python-service.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podLabels }}
      labels:
        {{- include "python-service.selectorLabels" . | nindent 8 }}
        {{- toYaml . | nindent 8 }}
      {{- else }}
      labels:
        {{- include "python-service.selectorLabels" . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "python-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.command }}
          args: {{ .Values.args }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 10 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
