# 仅安装mysql
# Global settings
global:
  environment: dev
  architecture: amd64
  imagePullSecrets:
    - name: registry-secret
  storageClass: "local-path"
  serviceAccount:
    create: false
    name: "default"
  database: mysql

registry:
  enabled: false  # 禁用自动创建 Secret
  server: "saascr.shukun.net"
  username: ""
  password: ""
  email: ""

middleware:
  enabled: true
  database:
    enabled: true
    serviceType: NodePort
    nodePort: 30306
  redis:
    enabled: false
  rabbitmq:
    enabled: false
  minio:
    enabled: false
data-foundation:
  enabled: false
model-foundation:
  enabled: false
common-foundation:
  enabled: false
medical-brain:
  enabled: false
biz-foundation:
  enabled: false
gateway:
  enabled: false
