apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hospital-web.fullname" . }}
  labels:
    {{- include "hospital-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hospital-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hospital-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthEndpoint }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.healthEndpoint }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
