apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $password := .Values.password | default (randAlphaNum 16) | b64enc }}
  mysql-root-password: {{ $password | quote }}
  mysql-password: {{ $password | quote }}
  mysql-database: {{ .Values.database | default "sk_agent" | b64enc }}
