{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "rabbitmq.fullname" . }}-pv
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    rabbitmq-pv: {{ include "rabbitmq.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.hostPath }}
{{- end }}
