apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.erlangCookie | default (randAlpha 32) | b64enc | quote }}
