{{- if .Values.service.headless }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      protocol: TCP
      name: management
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      protocol: TCP
      name: management
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
{{- end }}
