apiVersion: v2
name: minio
description: MinIO Object Storage (Bitnami)
version: 1.0.0
appVersion: "2023-03-20T20-16-18Z"
keywords:
  - minio
  - object storage
  - s3
dependencies:
  - name: minio
    version: "14.0.0"
    repository: "https://charts.bitnami.com/bitnami"