name: minio
image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 9000
env:
  - name: MINIO_ROOT_USER
    value: minioadmin
  - name: MINIO_ROOT_PASSWORD
    value: minioadmin123
volumes:
  - name: data
    mountPath: /data
    size: 20Gi
    storageClass: local-path
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
