name: redis

# storageClass (falls back to global.storageClass if empty)
storageClass: ""

image:
  repository: saascr.shukun.net/ghc/backend/sk-redis
  tag: 4.0.2
  pullPolicy: IfNotPresent

service:
  serviceType: NodePort
  port: 6379
  nodePort: 30379

env:
  - name: REDIS_PASSWORD
    value: "redis123"
volumes:
  - name: data
    mountPath: /data
    size: 2Gi
    storageClass: local-path
  - name: conf
    mountPath: /usr/local/etc/redis
    size: 100Mi
    storageClass: local-path
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
