{{- $accessKey := .Values.minio.accessKey | default "minioadmin" -}}
{{- $secretKey := .Values.minio.secretKey | default "minioadmin123" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ $accessKey | b64enc | quote }}
  secret-key: {{ $secretKey | b64enc | quote }}
